// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'firebase_options.dart';

Future<void> initializeFirebase() async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASHYX4zCVdW_MVxoO5rDtp_AlWOkRCCMc',
    appId: '1:728399425211:web:b8b5cbe1569c9a7987439e',
    messagingSenderId: '728399425211',
    projectId: 'pigsave-c4738',
    authDomain: 'pigsave-c4738.firebaseapp.com',
    storageBucket: 'pigsave-c4738.firebasestorage.app',
    measurementId: 'G-22NWVEV5WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2a2-h3z2ORcLcuinDP2s1TYnlL_j9q6I',
    appId: '1:728399425211:android:893ec82a8e18a01d87439e',
    messagingSenderId: '728399425211',
    projectId: 'pigsave-c4738',
    storageBucket: 'pigsave-c4738.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ1Z5eN7K3gCs2FaTnIKljUjPQA8Jp-L8',
    appId: '1:728399425211:ios:180ccc994506298b87439e',
    messagingSenderId: '728399425211',
    projectId: 'pigsave-c4738',
    storageBucket: 'pigsave-c4738.firebasestorage.app',
    iosClientId:
        '728399425211-62s4cjrrp2fi67uq4m7gnddi22n8811c.apps.googleusercontent.com',
    iosBundleId: 'com.example.pigsave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ1Z5eN7K3gCs2FaTnIKljUjPQA8Jp-L8',
    appId: '1:728399425211:ios:180ccc994506298b87439e',
    messagingSenderId: '728399425211',
    projectId: 'pigsave-c4738',
    storageBucket: 'pigsave-c4738.firebasestorage.app',
    iosClientId:
        '728399425211-62s4cjrrp2fi67uq4m7gnddi22n8811c.apps.googleusercontent.com',
    iosBundleId: 'com.example.pigsave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASHYX4zCVdW_MVxoO5rDtp_AlWOkRCCMc',
    appId: '1:728399425211:web:7ad560f32fb0c38f87439e',
    messagingSenderId: '728399425211',
    projectId: 'pigsave-c4738',
    authDomain: 'pigsave-c4738.firebaseapp.com',
    storageBucket: 'pigsave-c4738.firebasestorage.app',
    measurementId: 'G-8VVC7N9HFX',
  );
}
